### ISSUE TITLE
Bugfix/PR in PyInquirer breaks lobot

### ISSUE THREAD

**Issue by mrschue** [mrschue/lobot#1]
A change in the _prompt_toolkit_ package significantly changed in interface of the package. 
This leads to the pip-version of _PyInquirer_ requiring the outdate _prompt_toolkit==1.0.14_ (throwing compatibility issues with Jupyter).
 
Alternatively, a PR fixing this has been merged in the master branch of [_PyInquirer_](https://github.com/CITGuru/PyInquirer), resolving this issue when the github version is installed directly. 

It seems, however, that this changed the interface of _PyInquirers_ 'prompt':

```
Traceback (most recent call last):
  File "./lobot.py", line 530, in <module>
    chosen_instance = ask_instance(instances)
  File "./lobot.py", line 453, in ask_instance
    answer = prompt(instance_prompt)['instance'].split(" :: ")[0]
TypeError: 'module' object is not callable

```
ToDo:
- change _lobot_ to work nicely with new _PyInquirer_
- change readme to include issue and manual installation of _PyInquirer_

**Comment by mrschue** [comment]
Issue has been fixed in latest version. 
_prompt_ is now module and needs to be called as _prompt.prompt()_.

PyInquirer installation remark added to readme.
